### ISSUE TITLE
[BUG] Economics.API

### ISSUE THREAD

**Issue by bccfdea** [UnrealMultiple/TShockPlugin#558]
### 已阅须知 | Read the guidelines

- [X] 是 | Yes

### BUG可复现 | Bug is reproducible

- [X] 是 | Yes

### 插件最新 | Plugin is up-to-date

- [ ] 是 | Yes

### 插件名字 | Plugin Name

Economic.API

### 系统 | System

Windows

### 发生了什么? | What happened?

使用TSManager加入Economic.API插件时，无法启动显示报错。

### 如何复现 | How to reproduce

使用TSManager加入Economic.API插件时，无法启动显示报错。

### 期望的结果? | Expected result?

正常启动

### 文本日志 | Text log

```shell
无
```

### 控制台日志 | Console log

```shell
[11/09/24 23:22:03] [Server API] Error: Startup aborted due to an exception in the Server API initialization:
System.InvalidOperationException: Plugin "EconomicsAPI" has thrown an exception during initialization.
 ---> System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.Collections.Generic.Dictionary`2.ValueCollection.Enumerator.MoveNext()
   at EconomicsAPI.Utils.Helper.InitPluginAttributes()
   at EconomicsAPI.Economics.Initialize()
   at TerrariaApi.Server.PluginContainer.Initialize()
   at TerrariaApi.Server.ServerApi.Program.<>c__DisplayClass5_0.<Main>g__LoadPlugins|5()
   --- End of inner exception stack trace ---
   at TerrariaApi.Server.ServerApi.Program.<>c__DisplayClass5_0.<Main>g__LoadPlugins|5()
   at TerrariaApi.Server.ServerApi.Program.<>c__DisplayClass5_0.<Main>g__Initialize|4(String[] commandLineArgs, Main game)
   at TerrariaApi.Server.ServerApi.Program.<>c__DisplayClass5_0.<Main>b__3(orig_Initialize orig, Main instance)
```

**Comment by ACaiCat** [comment]
确认一下插件版本号

**Comment by bccfdea** [comment]
V2.0.0.0

**Comment by Controllerdestiny** [comment]
https://github.com/UnrealMultiple/TShockPlugin/actions/runs/11872120729

在这下载测试一下，我没有tsm。

**Comment by bccfdea** [comment]
OK了，谢谢
